export const END_POINTS = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  PROFILE: "/auth/profile",
  SENDOTP: "/auth/send-otp-email",
  VERIFYOTP: "/auth/verifyotp",
  PHONEOTP: "/auth/send-otp-number",
  VERIFYPHONE: "/auth/verifyPhoneotp",
  FORGETPASSWORD: "/auth/forgotPassword",
  RESETPASSWORD: "/auth/resetPassword",
  //vendor servcies lisiting
  SERVICELISTING: "/servicelisting",
  SERVICETYPE: "/serviceCatagory",
  AMENITY: "/amenity",
  GADGET: "/gadget",
  SERVICELIST: "/servicelisting",
  GET_ME: "/user/Me",
  DELETE_ME: "/user/Me",
  UPDATE_ME: "/user/Me",
  RESET_PASSWORD: "/auth/updateUserPassword",
  FAQ: "/Faq",
  KYC: "/kycRoute",
  ACCOUNT_USER: "/user/AccountUsers",
  DISPUTE: "/dispute",
  TEMPLATES: "/templete",
  SUBADMIN: "/subAdmin",
  COUNTRY: "/country",
  CITY: "/city",
  TAXFORUM: "/taxForum",
  ADVERTISEMENT: "/advertisement",
};
